### ISSUE TITLE
Please clean up your requirements.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/keylogger#1]
Exactly the same problem as per: kevinadhiguna/link-shortener#1 and kevinadhiguna/instagram-profpic-downloader#1 and kevinadhiguna/body-mass-index-calculator#1 and kevinadhiguna/ip-revealer#1 … the list has become long enough to not even include all. See the first referenced here for a full index of how bad this problem is.

Low quality bulk library creation with no use of the referenced libraries is pure spam.  Please correct this.

**Comment by kevinadhiguna** [comment]
Hello @amcgregor , I appreciate you for reporting this issue. I think the [latest commit](https://github.com/kevinadhiguna/keylogger/commit/da4f02f31e7dc02bf59cedc2dbf46a08130ecff1) has fixed this issue. Please let me know if you have any questions, thanks !

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭) Wave 2! 😀
